spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
